// Generated by gencpp from file baxter_challenge/BlockState.msg
// DO NOT EDIT!


#ifndef BAXTER_CHALLENGE_MESSAGE_BLOCKSTATE_H
#define BAXTER_CHALLENGE_MESSAGE_BLOCKSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace baxter_challenge
{
template <class ContainerAllocator>
struct BlockState_
{
  typedef BlockState_<ContainerAllocator> Type;

  BlockState_()
    : pose()
    , block_colour()
    , detected_colour()  {
    }
  BlockState_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , block_colour(_alloc)
    , detected_colour(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _block_colour_type;
  _block_colour_type block_colour;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _detected_colour_type;
  _detected_colour_type detected_colour;





  typedef boost::shared_ptr< ::baxter_challenge::BlockState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_challenge::BlockState_<ContainerAllocator> const> ConstPtr;

}; // struct BlockState_

typedef ::baxter_challenge::BlockState_<std::allocator<void> > BlockState;

typedef boost::shared_ptr< ::baxter_challenge::BlockState > BlockStatePtr;
typedef boost::shared_ptr< ::baxter_challenge::BlockState const> BlockStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_challenge::BlockState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_challenge::BlockState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_challenge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_challenge': ['/user/HS121/rw00636/baxterchallenge/src/baxter_challenge/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_challenge::BlockState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_challenge::BlockState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_challenge::BlockState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_challenge::BlockState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_challenge::BlockState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_challenge::BlockState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_challenge::BlockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64375395e16156e7524bad1bd00751b2";
  }

  static const char* value(const ::baxter_challenge::BlockState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64375395e16156e7ULL;
  static const uint64_t static_value2 = 0x524bad1bd00751b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_challenge::BlockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_challenge/BlockState";
  }

  static const char* value(const ::baxter_challenge::BlockState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_challenge::BlockState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
string block_colour\n\
string detected_colour\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::baxter_challenge::BlockState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_challenge::BlockState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.block_colour);
      stream.next(m.detected_colour);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlockState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_challenge::BlockState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_challenge::BlockState_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "block_colour: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.block_colour);
    s << indent << "detected_colour: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detected_colour);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_CHALLENGE_MESSAGE_BLOCKSTATE_H
