// Generated by gencpp from file baxter_challenge/ObjectInspectionResponse.msg
// DO NOT EDIT!


#ifndef BAXTER_CHALLENGE_MESSAGE_OBJECTINSPECTIONRESPONSE_H
#define BAXTER_CHALLENGE_MESSAGE_OBJECTINSPECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxter_challenge
{
template <class ContainerAllocator>
struct ObjectInspectionResponse_
{
  typedef ObjectInspectionResponse_<ContainerAllocator> Type;

  ObjectInspectionResponse_()
    : colour()  {
    }
  ObjectInspectionResponse_(const ContainerAllocator& _alloc)
    : colour(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _colour_type;
  _colour_type colour;





  typedef boost::shared_ptr< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInspectionResponse_

typedef ::baxter_challenge::ObjectInspectionResponse_<std::allocator<void> > ObjectInspectionResponse;

typedef boost::shared_ptr< ::baxter_challenge::ObjectInspectionResponse > ObjectInspectionResponsePtr;
typedef boost::shared_ptr< ::baxter_challenge::ObjectInspectionResponse const> ObjectInspectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxter_challenge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'baxter_challenge': ['/user/HS121/rw00636/baxterchallenge/src/baxter_challenge/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7b93667ab19d45333d9d3fab6d6a1fb";
  }

  static const char* value(const ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7b93667ab19d453ULL;
  static const uint64_t static_value2 = 0x33d9d3fab6d6a1fbULL;
};

template<class ContainerAllocator>
struct DataType< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxter_challenge/ObjectInspectionResponse";
  }

  static const char* value(const ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string colour\n\
\n\
";
  }

  static const char* value(const ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.colour);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInspectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxter_challenge::ObjectInspectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "colour: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.colour);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTER_CHALLENGE_MESSAGE_OBJECTINSPECTIONRESPONSE_H
